accounts/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views
app_name = 'accounts'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('signup/', views.signup, name='signup'),
    path('profile/', views.profile, name='profile'),
    path('genre/', views.genre, name='genre'),
]

lastProject/urls.py
from django.contrib import admin
from django.urls import path,include

from movies import views as movies_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', movies_views.home),
    path('accounts/', include('accounts.urls')),
    path('movies/', include('movies.urls')),
    path('about/', movies_views.about),
]

movies/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views
app_name= 'movies'
urlpatterns=[
    path('', views.index, name='index'),
    path('<int:movie_pk>/', views.detail, name='detail'),
    path('<int:movie_pk>/comment/', views.comment_create, name='c_comment'),
    path('<int:movie_pk>/like/', views.like, name='like'),
    path('<int:movie_pk>/comment/<int:comment_pk>/', views.comment_delete,name='c_delete'),
]

movies/models.py
from django.db import models
from django.conf import settings
# Create your models here.

class Movie(models.Model):
    movieid = models.IntegerField(primary_key=True )
    title = models.TextField()
    overview = models.TextField()
    original_title = models.TextField()
    popularity = models.FloatField()
    runtime = models.IntegerField()
    release_date = models.DateField()
    credit = models.TextField()
    genres = models.TextField()
    poster = models.TextField()         # 이거 model 하나 새로 만들기
    videos = models.TextField()
    keywords = models.TextField()
    score = models.FloatField(default = 0)
    like_users = models.ManyToManyField(
        settings.AUTH_USER_MODEL,
        related_name='like_movies',
        blank=True
    )


class Comment(models.Model):
    content= models.CharField(max_length=140)
    created_at = models.DateTimeField(auto_now_add=True)
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                                on_delete=models.CASCADE
                                )
    score = models.IntegerField()


class Genre(models.Model):
    name = models.TextField()
    
class Actor(models.Model):
    name = models.CharField(max_length=30)
    gender = models.IntegerField()
    images = models.URLField()

movies/forms.py
from django import forms
from .models import Movie, Comment

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        exclude = ('movie','user')

movies/views.py
from django.shortcuts import render,redirect,get_object_or_404
from .models import Movie, Genre
from accounts.forms import CustomUserCreationForm
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import AuthenticationForm
from IPython import embed
from .forms import CommentForm
from django.http import HttpResponse
from django.views.decorators.http import require_POST
import datetime
import requests
import random
# Create your views here.

def home(request):
    if request.user.is_authenticated:
        return redirect('movies:index')
    signupform = CustomUserCreationForm()
    loginform = AuthenticationForm()
    context = {
        'signupform': signupform,
        'loginform': loginform
    }
    return render(request, 'movies/home.html', context)

def index(request):
    User = get_user_model()
    user = get_object_or_404(User, username=request.user)
    if user.preference.all():
        now_list = getNow()
        movie_list = []
        for idx in user.preference.all():   
            genre_movie = {}
            genre_movie['genre'] = Genre.objects.get(id=idx.id).name
            movie = Movie.objects.filter(genres__contains= idx.id).order_by('-popularity')
            genre_movie['genre_movie_list'] = movie[:10]
            movie_list.append(genre_movie)
        context = {
            'movie_list' : movie_list,
            'now' : now_list
        }
        return render(request, 'movies/index.html', context)
    else:
        return redirect('accounts:genre')

def detail(request, movie_pk):
    movie = get_object_or_404(Movie, movieid=movie_pk)
    genre_list = []
    movie_genre_list = eval(movie.genres)
    for genre in movie_genre_list:
        genre_item = Genre.objects.get(id=genre)
        genre_list.append(genre_item.name)
    movie.genres = genre_list
    video_list = ''
    if eval(movie.videos):
        video_list = (eval(movie.videos)[0])
    movie.videos = video_list
    movie.credit = eval(movie.credit)
    re_movie = get_re(movie_pk)
    comments = movie.comment_set.all()

    context = {
        'movie': movie,
        're_movie' : re_movie,
        'comments' : comments,
    }
    
    return render(request,'movies/detail.html', context)
    
def getNow():
    yesterday = datetime.date.today() - datetime.timedelta(1)
    yesterday = yesterday.strftime('%Y%m%d')
    movie_list = []
    api_key = '407e887e6e33a30edd477d217f18d883'
    url = f'http://www.kobis.or.kr/kobisopenapi/webservice/rest/boxoffice/searchDailyBoxOfficeList.json?key={api_key}&targetDt={yesterday}&multiMovieYn=N'
    a = requests.get(url).json()
    response = requests.get(url).json().get('boxOfficeResult').get('dailyBoxOfficeList')
    api_key = '69855813cd52f7cdbc7e336c8afaac95'
    for movie in response:
        try:
            item = Movie.objects.get(title=movie.get('movieNm'))
            movie_list.append(item)
        except:
            movie_title = movie.get('movieNm')
            find_url = f'https://api.themoviedb.org/3/search/movie?api_key={api_key}&language=ko-KR&query={movie_title}&page=1&include_adult=true'
            response_2 = requests.get(find_url).json().get('results')
            if response_2:
                movie_id = response_2[0].get('id')
            else:
                continue
            detail_url = f'https://api.themoviedb.org/3/movie/{movie_id}?api_key={api_key}&language=ko-KR&append_to_response=videos%2Ccredits'
            response_detail = requests.get(detail_url).json()
            genre_list = []
            video_list = []
            for genre in response_detail.get('genres'):
                genre_list.append(genre.get('id'))
            a = response_detail.get('videos').get('results')
            if a:
                for movie in a:
                    video_list.append(movie.get('key'))
            else:
                detail_url2 = f'https://api.themoviedb.org/3/movie/{movie_id}?api_key={api_key}&language=en-US&append_to_response=videos%2Ccredits'
                response_detail_en = requests.get(detail_url2).json()
                if response_detail_en.get('videos').get('result'):
                    for movie in response_detail_en.get('videos').get('result'):
                        video_list.append(movie.get('key'))
            movie = Movie.objects.create(movieid=response_detail.get('id'),title=response_detail.get('title'), overview=response_detail.get('overview'), genres=genre_list, poster=response_detail.get('poster_path'), original_title=response_detail.get('original_title'), popularity= response_detail.get('popularity'), runtime= response_detail.get('runtime'), release_date=response_detail.get('release_date'), videos = video_list, credit = response_detail.get('credits').get('cast'))
            movie_list.append(movie)
    return movie_list

def get_re(a):
    api_key = '69855813cd52f7cdbc7e336c8afaac95'
    url = f'https://api.themoviedb.org/3/movie/{a}/recommendations?api_key={api_key}&language=ko-KR&page=1'
    response= requests.get(url).json().get('results')
    movie_list = []
    recommendation_list = []
    if not response:                                # 추천 영화 없으면
        return recommendation_list
    # if len(response) >= 10:
    #     for i in range(10):
    #         embed()
    #         movie_list.append(response[i].get('id'))
    # else:
    #     for i in range(len(response)):
    #         movie_list.append(response[i].get('id'))
    response = response[:10]
    for i in range(len(response)):
        movie_list.append(response[i].get('id'))
        
    for movie in movie_list:
        genre_list = []
        video_list = []
        try:
            item = Movie.objects.get(movieid=movie)
            recommendation_list.append(item)
        except:
            url = f'https://api.themoviedb.org/3/movie/{movie}?api_key={api_key}&language=ko-KR&append_to_response=videos%2Ccredits'
            #response = requests.get(url).json().get('result')
            response = requests.get(url).json()
            for genre in response.get('genres'):
                genre_list.append(genre.get('id'))
            videos = response.get('videos').get('results')
            if videos:
                for video in videos:
                    video_list.append(video.get('key'))
            else:
                url_en = f'https://api.themoviedb.org/3/movie/{movie}?api_key={api_key}&language=en-US&append_to_response=videos%2Ccredits'
                response_en = requests.get(url_en).json().get('videos').get('results')
                if response_en:
                    for video in response_en:
                        video_list.append(video.get('key'))
            movie_item = Movie.objects.create(movieid=movie, title=response.get('title'), overview=response.get('overview'), genres=genre_list, poster=response.get('poster_path'), original_title=response.get('original_title'), popularity=response.get('popularity'), runtime=response.get('runtime'), release_date = response.get('release_date'),videos=video_list,credit=response.get('credits').get('cast'))
            recommendation_list.append(movie_item)
    return recommendation_list

########################################댓글#########################
@require_POST
def comment_create(request, movie_pk):                          # 여기다가 평점도 저장해야 할듯
    if request.user.is_authenticated:
        movie = get_object_or_404(Movie, movieid=movie_pk)
        comment_form = CommentForm(request.POST)
        if comment_form.is_valid():
            comment = comment_form.save(commit=False)
            comment.movie = movie
            comment.user = request.user
            comment.save()
            num = len(movie.comment_set.all())
            movie.score = ((movie.score *(num - 1)) + comment.score) / num
            movie.save()
            return redirect('movies:detail', movie_pk)
        # 타당하지 않을 경우 Alert 창 띄우면 될것같은데...
    else:
        return HttpResponse('Unauthorized', status=401)


@require_POST   
def comment_delete(request, movie_pk, comment_pk):
    comment = Comment.objects.get(pk=comment_pk)
    comment.delete()
    return redirect('movies:detail', movie_pk)
########################################좋아요############################

def like(request, movie_pk):
    if request.user.is_authenticated:
        movie = get_object_or_404(Movie, movieid=movie_pk)
        if request.user in movie.like_users.all():
            movie.like_users.remove(request.user)
        else:
            movie.like_users.add(request.user)
        return redirect('movies:detail', movie_pk)
    else:
        return redirect('accounts:login')
###########################################################################

def recommendation_2(request):
    comments = get_object_or_404(Comment, user=request.user.id)
    high_list = []
    highest_val = -0xffffff
    for comment in comments:
        if comment.score > highest_val:
            high_list.clear()
            high_list.append(comment.movie)
            highest_val = comment.score
        elif comment.score == highest_val:
            high_list.append(comment.movie)
    
    if not len(high_list):
        lists = (Movie.objects.all().order_by('-score','-popularity'))[:10]
        return lists
    movie = random.choice(high_list)   
    keywords = Movie.objects.get(movieid=movie).get('keywords')
    recommendation_list = Movie.objects.filter(keyword__in=keywords).order_by('-score', '-popularity')
    if not recommendation_list:
        return []
    else:
        if len(recommendation_list) > 10:
            return recommendation_list[:10]
        else:
            return recommendation_list

movies/templates/movies/about.html
{% extends 'base.html' %}
{% load static %}

  {% block title %}
  <title>About</title>
  {% endblock %}

  {% block css%}
  <style>
    * {
      margin: 0;
    }
    body {
      height: 100vh;
      background: rgb(247, 247, 236);
    }
    p {
      font-size: 20px;
    }
    .my-container {
      margin: 0 300px;
    }
    .info-body {
      padding-top: 200px;
    }
    .info-card {
      background: white;
      border-radius: 10px;
      border-bottom: solid gray 3px;
      border-right: solid  gray 3px;
      margin-right: 100px;
    }
    .info-icon {
      font-size: 48px;
      margin-top: 10px;
      margin-right: 10px;
    }
    .back-to-project {
      position: absolute;
      left: 30px;
      top: 30px;
    }
    .back-to-project a {
      color: black;
    }

  </style>    
  {% endblock %}

{% block body %}
  <div class="back-to-project">
    <a href="{% url 'movies:index' %}"><h3>프로젝트로 돌아가기</h3></a>    
  </div>
  <div class="my-container">
    <div class="info-body">
      <div class="row">
        <div class="col-5 info-card">
          <div class="row py-3">
            <div class="col-5">
              <img  width="100%" src="{% static 'movies/images/bum.gif' %}">
            </div>
            <div class="col-7">
              <div class="row mt-3">
                <div class="col-8">
                  <h2>홍순범</h2>
                  <p>back-end</p>                  
                </div>
                <div class="col-4">
                  <a target="_blank" rel="noopener noreferrer" href="https://github.com/ssshhh0402" style="color: black;"><i class="fab fa-github" style="font-size: 4em"></i></a>
                </div>
              </div>
              <p>email: ssshhh0402@naver.com</p>
              <i class="fab fa-python info-icon animated heartBeat delay-5s slow"></i>
              <i class="fab fa-java info-icon animated heartBeat delay-5s slow"></i>
              <i class="fab fa-html5 info-icon animated heartBeat delay-5s slow"></i>
              <i class="fab fa-css3-alt info-icon animated heartBeat delay-5s slow"></i>
              <i class="fab fa-js-square info-icon animated heartBeat delay-5s slow"></i>
              <i class="fab fa-react info-icon animated heartBeat delay-5s slow"></i>
            </div>
          </div>
        </div>
        <div class="col-5 info-card">
          <div class="row py-3">
            <div class="col-5">
              <img  width="100%" src="{% static 'movies/images/woo.jpg' %}">
            </div>
            <div class="col-7">
              <div class="row mt-3">
                <div class="col-8">
                  <h2>김태우</h2>
                  <p>front-end</p>                  
                </div>
                <div class="col-4">
                  <a target="_blank" rel="noopener noreferrer" href="https://github.com/EHwooKim" style="color: black;"><i class="fab fa-github" style="font-size: 4em"></i></a>
                </div>
              </div>
              <p>email: ehwoo0707@naver.com</p>
              <i class="fab fa-python info-icon animated hinge delay-4s"></i>
              <i class="fab fa-html5 info-icon animated hinge delay-2s"></i>
              <i class="fab fa-css3-alt info-icon animated hinge delay-3s"></i>
              <i class="fab fa-js-square info-icon animated hinge delay-1s"></i>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>


  <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.0/js/bootstrap.min.js" integrity="sha384-3qaqj0lc6sV/qpzrc1N5DC6i1VRn/HyX4qdPaiEFbn54VjQBEU341pvjz7Dv3n6P" crossorigin="anonymous"></script>  
{% endblock %}

movies/templates/movies/detail.html
{% extends 'base.html' %}
{% load static %}
  {% block title %}
  <title>영화 상세보기</title>
  {% endblock %}
  {% block css %}
  <style>
    body {
      background: #131313;    
    }
    * {
      color: white;
    }
    p {
      font-size: 1.2rem;
    }
    .en-title {
      font-size: 25px;
    }
    hr {
      color: white;
      border-color: white;
      background-color: white;
    }
    .comment {
      color: white;
    }
    .poster-img {
      transition: all 0.5s;
    }
    .poster-img:hover {
      transform: scale(1.1);
    }
  </style>
  {% endblock %}

  {% block body %}
  {% include '_navbar.html' %}
  <div class="container border border-dark">
    <div class="row mt-5">
      <div class="col-4">
          <img src="https://image.tmdb.org/t/p/w300{{movie.poster}}">
      </div>
      <div class="col-8">
          <h1>{{movie.title}} <span class="en-title">({{movie.original_title}})</span></h1>
          <p>장르:
            {% for genre in movie.genres %} 
            <span>{{genre}}</span>
            {% endfor %}
          </p>
          <p>{{movie.overview}} </p>
          <p>인기도: {{movie.popularity}}</p>
          <p>상영시간: {{movie.runtime}}분</p>
          <p>개봉일: {{movie.release_date}}</p>
          {% if user in movie.like_users.all %}
          <button id="like-button" data-id="{{movie.movieid}}" type="button" class="btn btn-success">좋아요 취소</button>
          {% else %}
          <button id="like-button" data-id="{{movie.movieid}}" type="button" class="btn btn-secondary">좋아요</button>
          {% endif %}
      </div>
    </div> 
    {% if movie.videos %}
    <div class='mt-3'>
      <hr>
      <h1>예고편</h1>
      <div style="text-align: center;">
        <iframe width="1000" height="600" src="https://www.youtube.com/embed/{{movie.videos}}" frameborder="0" allowfullscreen></iframe>
      </div>    
    </div> 
    {% endif %}
    {% if re_movie %}
    <div class="mt-3">
      <hr>
      <h1>추천영화</h1>
      <div class="row">
        {% for movie in re_movie %}
          <div class="col-2">
            <a href="{% url 'movies:detail' movie.pk %}"><img width="100%" class="poster-img" src="https://image.tmdb.org/t/p/w200{{movie.poster}}"></a>
            <p class="mt-2">{{movie.title}}</p>
          </div>
        {% endfor %}
      </div>
    </div>
    {% endif %}
    <div class="mt-3">
      <hr>
      <h1>출연진</h1>
      <div class="row">
      {% for item in movie.credit %}
        <div class="col-2">
          {% if item.profile_path %}
          <img  width="100%" src="https://image.tmdb.org/t/p/w200{{item.profile_path}}">
          {% else %}
          <img  width="100%" src="{% static 'movies/images/unknown.jpg' %}">
          {% endif %}
          <p>{{item.name}}</p>
        </div>
      {% endfor %}
      </div>
    </div>
    <div class="mt-3">
    <hr>
    <h1>평점</h1>
      {% if user not in movie.comment_set.all %}
    <div>
      <form action="{% url 'movies:c_comment' movie.pk %}" method="POST">
        {% csrf_token%}
        <div class="row">
          <div class="form-group col-2">
            <label class="comment" class="score" for="content">평점 </label>
            <input type="number" class="form-control" id="score" name="score">
          </div>
          <div class="form-group col-10">
            <label class="comment" for="content">댓글</label>
            <input type="text" class="form-control" id="content" placeholder="댓글 작성" name="content">
          </div>
        </div>
        <input class="d-block btn btn-dark ml-auto mt-2 " type="submit" value="등록">
      </form>
    </div>
    {% else %}
    <div class="comment-block">
      <h3>이미 리뷰를 등록한 영화입니다.</h3>
    </div>
    {% endif %}
    {% for comment in comments %}
      <span>{{comment.user}} | {{comment.score}}점 | {{comment.content}} </span>
      {% if user == comment.user %}
      <form action="{% url 'movies:c_delete' comment.movie.movieid comment.pk %}" method="POST" class="d-inline">
        {% csrf_token %}
        <button type="submit" class="btn btn-dark d-inline">평점삭제</button>
      </form>
      <hr>
      {% endif %}
    {% endfor %}
    </div>
  </div>
  {% include '_footer.html' %}
  {% endblock %}

  {% block script %}  
  <script>
    const likeButton = document.querySelector('#like-button')
    likeButton.addEventListener('click', function(event) {
      axios.get(`/movies/${event.target.dataset.id}/like`)
        .then(response => {
          if(response.data.is_liked) {
            event.target.classList.remove('btn-secondary')
            event.target.classList.add('btn-success')
            event.target.innerText = '좋아요 취소'
          } else {
            event.target.classList.remove('btn-success')
            event.target.classList.add('btn-secondary')
            event.target.innerText = '좋아요'
          }
        })
        .catch(error => {
          console.log(error)
        })
      })
  </script>
  {% endblock %}

movies/templates/movies/genre.html
{% load static %}

<!DOCTYPE html>
<html lang="ko">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <link rel="stylesheet" href="{% static 'movies/css/genre_style.css' %}">
  <title>Genre</title>
</head>
<body>
  <!-- display:none 시킬 form들-->
  <form action="">
    {% for genre in Genres %}
    <input type="checkbox" name="genre" value='genre.id' id="{{genre.name}}">
    {% endfor %}
    <input class="genre-submit" type="submit" value="저장">
  </form>
  <!-- 메인 div -->
  <header>

  </header>
  <div class="genre-bg">
    <div class="container">
      <div class="row">
        {% for genre in Genres %}
          <div class="genre_box col-2">
            <label for="{{genre.name}}" onClick="count_ck(this)">{{genre.name}}</label>
          </div>
        {% endfor %}
      </div>
    </div>
  </div>

  <footer>
  </footer>


  <script>
  function count_ck(obj){
  var chkbox = document.getElementsByName("genre");
  var chkCnt = 0;
  for(var i=0;i<chkbox.length; i++){
    if(chkbox[i].checked){
        chkCnt++;
      }
    }
    if(chkCnt>2){
      alert("장르는 3개까지 선택 가능합니다.");
      obj.checked = false;
      return false;
    }
  }
  </script>
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script> 
</body>
</html>

movies/templates/movies/home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <link href="https://fonts.googleapis.com/css?family=Noto+Sans+KR|Noto+Serif+KR|Sunflower:300&display=swap" rel="stylesheet">
  <!-- <link rel="stylesheet" href="{% static 'movies/css/home_style.css' %}"> -->
  <title>Document</title>
  <style>
    * {
      font-family: 'Sunflower', sans-serif;
    }     
    body {
      height: 100vh;
    }
    .home-bg-01 {
      height: 100%;
    }
    .div01 {
      height: 100%;
      width: 100%;
      color: white;
      padding: 100px 200px;
      background-image: url('/static/movies/images/harry_potter.png');
      background-attachment: fixed;                                                                                                                                                                   
      background-position-y: -150px;
    }
    div.sticky {
      position: sticky;
      top: 0;
      height: 50px;
      background-color: black;
      color: white;
      font-size: 15px;
      line-height: 50px;
    }
    .form-bg-left {
      height: 100%;
      background-color: rgba(0, 0, 0, 0.7);
    }
    .form-bg-right {
      height: 100%;
      padding: 30px 70px;
      background-color: rgba(0, 0, 0, 0.7);
    }
    .signup-form {
      opacity: 1 !important;
    }
    .login-form {
      opacity: 1 !important;
      display: none;
    }
  </style>
</head>
<body>
  <div class="div01">
    <div class="home-bg-01 row">
      <div class="col-7 form-bg-left text-center">
        <i class="fas fa-database" style="font-size: 70px;"></i>
        <i class="fas fa-film" style="font-size: 70px;"></i>
        <i class="fas fa-user-alt"  style="font-size: 70px;"></i>
      </div>
      <div class="col-1"></div>
      <div class="col-4 form-bg-right">
        <div class="signup-form">
          <h2>회원가입</h2>
          <!-- 다음에 다시 와서 form 바꾸자 -->
          <form action="{% url 'accounts:signup' %}" method="POST">
            {% csrf_token %}
            <div class="form-group">
              <label for="username">아이디</label>
              <input type="text" class="form-control" id="username" placeholder="아이디" name="username">
            </div>
            <div class="form-group">
              <label for="email">이메일주소</label>
              <input type="email" class="form-control" id="email" placeholder="이메일" name="email">
            </div>
            <div class="form-group">
              <label for="last_name">성</label>
              <input type="text" class="form-control" id="last_name" placeholder="성" name="last_name">
            </div>
            <div class="form-group">
              <label for="first_name">이름</label>
              <input type="text" class="form-control" id="first_name" placeholder="이름" name="first_name">
            </div>
            <div class="form-group">
              <label for="password1">비밀번호</label>
              <input type="password" class="form-control" id="password1" placeholder="비밀번호" name="password1">
            </div>
            <div class="form-group">
              <label for="password2">비밀번호 확인</label>
              <input type="password" class="form-control" id="password2" placeholder="비밀번호확인" name="password2">
            </div>
            <div class="text-right">
            <input type="submit" class="btn btn-info" value="회원가입">
            <br><br>
            <p class="">이미 회원이시라면 <span id="login-change" class="text-warning">로그인</span></p>
            </div>
          </form>
        </div>
        <div class="login-form">
          <h2>로그인</h2>
          <form action="{% url 'accounts:login' %}" method="POST">
            {% csrf_token %}
            <div class="form-group">
              <label for="username">아이디</label>
              <input type="text" class="form-control" id="username" placeholder="아이디" name="username">
            </div>
            <div class="form-group">
              <label for="password">비밀번호</label>
              <input type="password" class="form-control" id="password" placeholder="비밀번호" name="password">
            </div>
            <div class="text-right">
              <input type="submit" class="btn btn-info" value="로그인">
              <br><br>
              <p class="">아직 회원이 아니라면 <span id="signup-change" class="text-warning">회원가입</span></p>            
          </form>
        </div>

      </div>
    </div>
  </div>
  <script>
    const login = document.querySelector('#login-change')
    const signup = document.querySelector('#signup-change')

    const loginForm = document.querySelector('.login-form')
    const signupForm = document.querySelector('.signup-form')

    login.addEventListener('click', function(event) {
      loginForm.style.display = "inline"
      signupForm.style.display = "none"
    })

    signup.addEventListener('click', function(event) {
      signupForm.style.display = "inline"
      loginForm.style.display = "none"
    })
  </script>
  <script src="https://kit.fontawesome.com/f7a84a7607.js" crossorigin="anonymous"></script>
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script> 
</body>
</html>