accounts/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views
app_name = 'accounts'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('signup/', views.signup, name='signup'),
    path('profile/', views.profile, name='profile'),
    path('genre/', views.genre, name='genre'),
]

lastProject/urls.py
from django.contrib import admin
from django.urls import path,include

from movies import views as movies_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', movies_views.home),
    path('accounts/', include('accounts.urls')),
    path('movies/', include('movies.urls')),
    path('about/', movies_views.about),
]

movies/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views
app_name= 'movies'
urlpatterns=[
    path('', views.index, name='index'),
    path('<int:movie_pk>/', views.detail, name='detail'),
    path('<int:movie_pk>/comment/', views.comment_create, name='c_comment'),
    path('<int:movie_pk>/like/', views.like, name='like'),
    path('<int:movie_pk>/comment/<int:comment_pk>/', views.comment_delete,name='c_delete'),
]

movies/models.py
from django.db import models
from django.conf import settings
# Create your models here.

class Movie(models.Model):
    movieid = models.IntegerField(primary_key=True )
    title = models.TextField()
    overview = models.TextField()
    original_title = models.TextField()
    popularity = models.FloatField()
    runtime = models.IntegerField()
    release_date = models.DateField()
    credit = models.TextField()
    genres = models.TextField()
    poster = models.TextField()         # 이거 model 하나 새로 만들기
    videos = models.TextField()
    keywords = models.TextField()
    score = models.FloatField(default = 0)
    like_users = models.ManyToManyField(
        settings.AUTH_USER_MODEL,
        related_name='like_movies',
        blank=True
    )


class Comment(models.Model):
    content= models.CharField(max_length=140)
    created_at = models.DateTimeField(auto_now_add=True)
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                                on_delete=models.CASCADE
                                )
    score = models.IntegerField()


class Genre(models.Model):
    name = models.TextField()
    
class Actor(models.Model):
    name = models.CharField(max_length=30)
    gender = models.IntegerField()
    images = models.URLField()

movies/forms.py
from django import forms
from .models import Movie, Comment

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        exclude = ('movie','user')

movies/views.py
from django.shortcuts import render,redirect,get_object_or_404
from .models import Movie, Genre
from accounts.forms import CustomUserCreationForm
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import AuthenticationForm
from IPython import embed
from .forms import CommentForm
from django.http import HttpResponse
from django.views.decorators.http import require_POST
import datetime
import requests
import random
# Create your views here.

def home(request):
    if request.user.is_authenticated:
        return redirect('movies:index')
    signupform = CustomUserCreationForm()
    loginform = AuthenticationForm()
    context = {
        'signupform': signupform,
        'loginform': loginform
    }
    return render(request, 'movies/home.html', context)

def index(request):
    User = get_user_model()
    user = get_object_or_404(User, username=request.user)
    if user.preference.all():
        now_list = getNow()
        movie_list = []
        for idx in user.preference.all():   
            genre_movie = {}
            genre_movie['genre'] = Genre.objects.get(id=idx.id).name
            movie = Movie.objects.filter(genres__contains= idx.id).order_by('-popularity')
            genre_movie['genre_movie_list'] = movie[:10]
            movie_list.append(genre_movie)
        context = {
            'movie_list' : movie_list,
            'now' : now_list
        }
        return render(request, 'movies/index.html', context)
    else:
        return redirect('accounts:genre')

def detail(request, movie_pk):
    movie = get_object_or_404(Movie, movieid=movie_pk)
    genre_list = []
    movie_genre_list = eval(movie.genres)
    for genre in movie_genre_list:
        genre_item = Genre.objects.get(id=genre)
        genre_list.append(genre_item.name)
    movie.genres = genre_list
    video_list = ''
    if eval(movie.videos):
        video_list = (eval(movie.videos)[0])
    movie.videos = video_list
    movie.credit = eval(movie.credit)
    re_movie = get_re(movie_pk)
    comments = movie.comment_set.all()

    context = {
        'movie': movie,
        're_movie' : re_movie,
        'comments' : comments,
    }
    
    return render(request,'movies/detail.html', context)
    
def getNow():
    yesterday = datetime.date.today() - datetime.timedelta(1)
    yesterday = yesterday.strftime('%Y%m%d')
    movie_list = []
    api_key = '407e887e6e33a30edd477d217f18d883'
    url = f'http://www.kobis.or.kr/kobisopenapi/webservice/rest/boxoffice/searchDailyBoxOfficeList.json?key={api_key}&targetDt={yesterday}&multiMovieYn=N'
    a = requests.get(url).json()
    response = requests.get(url).json().get('boxOfficeResult').get('dailyBoxOfficeList')
    api_key = '69855813cd52f7cdbc7e336c8afaac95'
    for movie in response:
        try:
            item = Movie.objects.get(title=movie.get('movieNm'))
            movie_list.append(item)
        except:
            movie_title = movie.get('movieNm')
            find_url = f'https://api.themoviedb.org/3/search/movie?api_key={api_key}&language=ko-KR&query={movie_title}&page=1&include_adult=true'
            response_2 = requests.get(find_url).json().get('results')
            if response_2:
                movie_id = response_2[0].get('id')
            else:
                continue
            detail_url = f'https://api.themoviedb.org/3/movie/{movie_id}?api_key={api_key}&language=ko-KR&append_to_response=videos%2Ccredits'
            response_detail = requests.get(detail_url).json()
            genre_list = []
            video_list = []
            for genre in response_detail.get('genres'):
                genre_list.append(genre.get('id'))
            a = response_detail.get('videos').get('results')
            if a:
                for movie in a:
                    video_list.append(movie.get('key'))
            else:
                detail_url2 = f'https://api.themoviedb.org/3/movie/{movie_id}?api_key={api_key}&language=en-US&append_to_response=videos%2Ccredits'
                response_detail_en = requests.get(detail_url2).json()
                if response_detail_en.get('videos').get('result'):
                    for movie in response_detail_en.get('videos').get('result'):
                        video_list.append(movie.get('key'))
            movie = Movie.objects.create(movieid=response_detail.get('id'),title=response_detail.get('title'), overview=response_detail.get('overview'), genres=genre_list, poster=response_detail.get('poster_path'), original_title=response_detail.get('original_title'), popularity= response_detail.get('popularity'), runtime= response_detail.get('runtime'), release_date=response_detail.get('release_date'), videos = video_list, credit = response_detail.get('credits').get('cast'))
            movie_list.append(movie)
    return movie_list

def get_re(a):
    api_key = '69855813cd52f7cdbc7e336c8afaac95'
    url = f'https://api.themoviedb.org/3/movie/{a}/recommendations?api_key={api_key}&language=ko-KR&page=1'
    response= requests.get(url).json().get('results')
    movie_list = []
    recommendation_list = []
    if not response:                                # 추천 영화 없으면
        return recommendation_list
    # if len(response) >= 10:
    #     for i in range(10):
    #         embed()
    #         movie_list.append(response[i].get('id'))
    # else:
    #     for i in range(len(response)):
    #         movie_list.append(response[i].get('id'))
    response = response[:10]
    for i in range(len(response)):
        movie_list.append(response[i].get('id'))
        
    for movie in movie_list:
        genre_list = []
        video_list = []
        try:
            item = Movie.objects.get(movieid=movie)
            recommendation_list.append(item)
        except:
            url = f'https://api.themoviedb.org/3/movie/{movie}?api_key={api_key}&language=ko-KR&append_to_response=videos%2Ccredits'
            #response = requests.get(url).json().get('result')
            response = requests.get(url).json()
            for genre in response.get('genres'):
                genre_list.append(genre.get('id'))
            videos = response.get('videos').get('results')
            if videos:
                for video in videos:
                    video_list.append(video.get('key'))
            else:
                url_en = f'https://api.themoviedb.org/3/movie/{movie}?api_key={api_key}&language=en-US&append_to_response=videos%2Ccredits'
                response_en = requests.get(url_en).json().get('videos').get('results')
                if response_en:
                    for video in response_en:
                        video_list.append(video.get('key'))
            movie_item = Movie.objects.create(movieid=movie, title=response.get('title'), overview=response.get('overview'), genres=genre_list, poster=response.get('poster_path'), original_title=response.get('original_title'), popularity=response.get('popularity'), runtime=response.get('runtime'), release_date = response.get('release_date'),videos=video_list,credit=response.get('credits').get('cast'))
            recommendation_list.append(movie_item)
    return recommendation_list

########################################댓글#########################
@require_POST
def comment_create(request, movie_pk):                          # 여기다가 평점도 저장해야 할듯
    if request.user.is_authenticated:
        movie = get_object_or_404(Movie, movieid=movie_pk)
        comment_form = CommentForm(request.POST)
        if comment_form.is_valid():
            comment = comment_form.save(commit=False)
            comment.movie = movie
            comment.user = request.user
            comment.save()
            num = len(movie.comment_set.all())
            movie.score = ((movie.score *(num - 1)) + comment.score) / num
            movie.save()
            return redirect('movies:detail', movie_pk)
        # 타당하지 않을 경우 Alert 창 띄우면 될것같은데...
    else:
        return HttpResponse('Unauthorized', status=401)


@require_POST   
def comment_delete(request, movie_pk, comment_pk):
    comment = Comment.objects.get(pk=comment_pk)
    comment.delete()
    return redirect('movies:detail', movie_pk)
########################################좋아요############################

def like(request, movie_pk):
    if request.user.is_authenticated:
        movie = get_object_or_404(Movie, movieid=movie_pk)
        if request.user in movie.like_users.all():
            movie.like_users.remove(request.user)
        else:
            movie.like_users.add(request.user)
        return redirect('movies:detail', movie_pk)
    else:
        return redirect('accounts:login')
###########################################################################

def recommendation_2(request):
    comments = get_object_or_404(Comment, user=request.user.id)
    high_list = []
    highest_val = -0xffffff
    for comment in comments:
        if comment.score > highest_val:
            high_list.clear()
            high_list.append(comment.movie)
            highest_val = comment.score
        elif comment.score == highest_val:
            high_list.append(comment.movie)
    
    if not len(high_list):
        lists = (Movie.objects.all().order_by('-score','-popularity'))[:10]
        return lists
    movie = random.choice(high_list)   
    keywords = Movie.objects.get(movieid=movie).get('keywords')
    recommendation_list = Movie.objects.filter(keyword__in=keywords).order_by('-score', '-popularity')
    if not recommendation_list:
        return []
    else:
        if len(recommendation_list) > 10:
            return recommendation_list[:10]
        else:
            return recommendation_list

movies/templates/_footer.html
<style>
  * {
    margin: 0;
    color: white;
  }
  .my-footer {
    margin-top: 80px;
    background: black;
    height: 100px;
  }
  .about-us {
    color: #ffc107;
    font-weight: bold;
    font-size: 20px;
  }
  .copyright {
    font-size: 16px;
  }
</style>    
  <div class="my-footer">
    <div class="container">
      <div class="row pt-3">
        <div class="col-4">
          <a href="/about/" class="about-us">About us</a>
        </div>
        <div class="col-4"></div>
        <div class="col-4"></div>
      </div>
      <div class="mt-3">
        <p class="copyright"> ⓒ Copyright by ehwoo-ssshhh</p>
      </div>
    </div>
  </div>  

movies/templates/_lion.html
<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <title>Ryan Login</title>
    <link rel="stylesheet" href="../static/movies/css/lion_style.css">
</head>
<body>
    <form>
        <svg id="ryan" viewBox="0 0 120 120" xmlns="http://www.w3.org/2000/svg">
            <path d="M0,150 C0,65 120,65 120,150" fill="#e0a243" stroke="#000" stroke-width="2.5" />
            <g class="ears">
                <path d="M46,32 L46,30 C46,16 26,16 26,30 L26,32" fill="#e0a243" stroke="#000" stroke-width="2.5" stroke-linecap="round" transform="rotate(-10,38,24)" />
                <path d="M74,32 L74,30 C74,16 94,16 94,30 L94,32" fill="#e0a243" stroke="#000" stroke-width="2.5" stroke-linecap="round" transform="rotate(10,82,24)" />
            </g>
            <circle cx="60" cy="60" r="40" fill="#e0a243" stroke="#000" stroke-width="2.5" />
            <g class="eyes">
                <!-- left eye and eyebrow-->
                <line x1="37" x2="50" y1="46" y2="46" stroke="#000" stroke-width="3" stroke-linecap="round" />
                <circle cx="44" cy="55" r="3" fill="#000" />
                <!-- right eye and eyebrow -->
                <line x1="70" x2="83" y1="46" y2="46" stroke="#000" stroke-width="3" stroke-linecap="round" />
                <circle cx="76" cy="55" r="3" fill="#000" />
            </g>
            <g class="muzzle">
                <path d="M60,66 C58.5,61 49,63 49,69 C49,75 58,77 60,71 M60,66 C61.5,61 71,63 71,69 C71,75 62,77 60,71" fill="#fff" />
                <path d="M60,66 C58.5,61 49,63 49,69 C49,75 58,77 60,71 M60,66 C61.5,61 71,63 71,69 C71,75 62,77 60,71" fill="#fff" stroke="#000" stroke-width="2.5" stroke-linejoin="round" stroke-linecap="round" />
                <polygon points="59,63.5,60,63.4,61,63.5,60,65" fill="#000" stroke="#000" stroke-width="5" stroke-linejoin="round" />
            </g>
            <path d="M40,105 C10,140 110,140 80,105 L80,105 L70,111 L60,105 L50,111 L40,105" fill="#fff" />
        </svg>
        <input type="text" placeholder="email@domain.com">
        <input type="password" placeholder="Password">
    </form>
    <script src="../static/movies/js/lion_script.js"></script>
</body>
</html>

movies/templates/_navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="{% url 'movies:index' %}">Movie</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          {{user.username}}
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="{% url 'accounts:profile' %}" >프로필</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="{% url 'accounts:logout' %}">로그아웃</a>
        </div>
      </li>
    </ul>
    <!-- <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>  검색기능 !!!!! --> 
  </div>
</nav>

movies/templates/base.html
<!DOCTYPE html>
<html lang="ko">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.0/css/bootstrap.min.css" integrity="sha384-SI27wrMjH3ZZ89r4o+fGIJtnzkAnFs3E4qz9DIYioCQ5l9Rd/7UAa8DHcaL8jkWt" crossorigin="anonymous">
  <link href="https://fonts.googleapis.com/css?family=Noto+Sans+KR|Noto+Serif+KR|Sunflower:300&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.7.2/animate.min.css">
  <style>
    * {
      font-family: 'Sunflower', sans-serif;
    }
  </style>
  {% block css %}
  {% endblock %}  

  {% block title %}
  {% endblock %}
</head>
<body>
  {% block body %}  
  {% endblock %}

  {% block script %}  
  {% endblock %}
  <script src="https://kit.fontawesome.com/f7a84a7607.js" crossorigin="anonymous"></script>
  <script src="https://unpkg.com/axios/dist/axios.min.js"></script>
  <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.0/js/bootstrap.min.js" integrity="sha384-3qaqj0lc6sV/qpzrc1N5DC6i1VRn/HyX4qdPaiEFbn54VjQBEU341pvjz7Dv3n6P" crossorigin="anonymous"></script>  
</body>
</html>