accounts/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views
app_name = 'accounts'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('signup/', views.signup, name='signup'),
    path('profile/', views.profile, name='profile'),
    path('genre/', views.genre, name='genre'),
]

lastProject/urls.py
from django.contrib import admin
from django.urls import path,include

from movies import views as movies_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', movies_views.home),
    path('accounts/', include('accounts.urls')),
    path('movies/', include('movies.urls')),
    path('about/', movies_views.about),
]

movies/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views
app_name= 'movies'
urlpatterns=[
    path('', views.index, name='index'),
    path('<int:movie_pk>/', views.detail, name='detail'),
    path('<int:movie_pk>/comment/', views.comment_create, name='c_comment'),
    path('<int:movie_pk>/like/', views.like, name='like'),
    path('<int:movie_pk>/comment/<int:comment_pk>/', views.comment_delete,name='c_delete'),
]

accounts/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import AbstractUser
from movies.models import Genre
# Create your models here.


class User(AbstractUser):
    preference = models.ManyToManyField(
        Genre,
        related_name='preferences',
        blank=True
    )

movies/models.py
from django.db import models
from django.conf import settings
# Create your models here.

class Movie(models.Model):
    movieid = models.IntegerField(primary_key=True )
    title = models.TextField()
    overview = models.TextField()
    original_title = models.TextField()
    popularity = models.FloatField()
    runtime = models.IntegerField()
    release_date = models.DateField()
    credit = models.TextField()
    genres = models.TextField()
    poster = models.TextField()         # 이거 model 하나 새로 만들기
    videos = models.TextField()
    keywords = models.TextField()
    score = models.FloatField(default = 0)
    like_users = models.ManyToManyField(
        settings.AUTH_USER_MODEL,
        related_name='like_movies',
        blank=True
    )


class Comment(models.Model):
    content= models.CharField(max_length=140)
    created_at = models.DateTimeField(auto_now_add=True)
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                                on_delete=models.CASCADE
                                )
    score = models.IntegerField()


class Genre(models.Model):
    name = models.TextField()
    
class Actor(models.Model):
    name = models.CharField(max_length=30)
    gender = models.IntegerField()
    images = models.URLField()

accounts/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm, UserChangeForm

class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = get_user_model()
        
        fields = ('username','first_name','last_name','email')

class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = get_user_model()
        field = '__all__'
        fields = ('username','email','preference')

accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import get_user_model
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth.forms import AuthenticationForm
from .forms import CustomUserCreationForm, CustomUserChangeForm
from IPython import embed
from movies.models import Genre
# Create your views here.

def login(request):
    form = AuthenticationForm(request.POST, data=request.POST)
    if form.is_valid():
        user = form.get_user()
        auth_login(request, user)
        if not user.preference.all():
            return redirect('accounts:genre')
        else:
            return redirect('movies:index')
    else:
        return redirect('/')
    

def signup(request):            #'GET'이면 폼보여주고
                                        #'POST'면 입력받은 정보 저장하면서 로그인 진행
    form = CustomUserCreationForm(request.POST)
    if form.is_valid():
        user = form.save()
        auth_login(request, user)
        return redirect('accounts:genre')
    else:
        # 비밀번호가 잘못됐습니다 경고문 띄우기
        return render(request, 'movies/home.html')

def genre(request):
    genres = Genre.objects.all()
    context = {
        'genres': genres
    }
    if request.method == 'POST':
        user = request.user
        genres = request.POST.getlist('genre')
        for pk in genres:
            user.preference.add(pk)
        return redirect('movies:index')
    else:
        return render(request, 'accounts/genre.html', context)

def logout(request):
    auth_logout(request)
    return redirect('/')
    
def profile(request):                    # request.user의 정보 받아오기
    User = get_user_model()
    user = get_object_or_404(User, pk=request.user.pk)
    context = {
        'user' : user
    }
    return render(request, 'accounts/profile.html', context)
        
# def update(request):                       # POST 면 변경 후 바뀐 프로필 보여주기
#                                                     # GET이면 유저 정보 변경 Form 보여주기
#     if request.method == 'POST':                   
#         form = CustomUserChangeForm(request.POST, instance=request.user)
#         if form.is_valid():
#             form.save()
#             return redirect('accounts:profile')
#     else:
#         form = CustomUserChangeForm(instance=request.user)
#     context = {
#         'form' : form
#     }
#     return render(request, 'accounts/form.html', context)

accounts/templates/accounts/genre.html
{% extends 'base.html' %}
{% load static %}
  {% block title%}
  <title>장르선택</title>
  {% endblock %}
  {% block css %}
  <style>
    * {
      font-family: 'Sunflower', sans-serif;
    }
    body {
      height: 100vh;
      background-color: black;
    }
    .genre-bg {
      height: 86%;
      background-color: #131313;
      background-size: cover;
      background-repeat: no-repeat;
    }
    .genre_box {
      height: 200px;
      padding: 20px;
      transition: all 1s;
    }
    input[type="checkbox"] {
      display: none;
    } 
    label {
      width: 150px;
      height: 150px;
      line-height: 150px;
      font-size: 1.5rem;
      background-color: black;
      opacity: .6;
      text-align: center;
      color: white;
      transition: all 0.6s;
    }
    label:hover {
      opacity: .8;
    }
    .select-label {
      opacity: 1 !important;
      color: #ffc107;
      border-radius: 100%;
    }
    header {
      height: 7%;
      background-color: black;
    }
    footer {
      height: 7%;
      background-color: black;
    }
    .genre-p {
      display:inline;
      position: absolute;
      top: 15px;
      right: 40px;      
      color: white;
      font-size: 23px;
      font-weight: bold;
      animation: change-color 2s infinite;
      animation-direction: alternate;
    }
    @keyframes change-color {
      0%   {color:  #fff; }
      100% {color:  #cf5763; }
    }    
    .genre-submit {
      display: none;
      position: absolute;
      top: 15px;
      right: 40px;
    }
  </style>
  {% endblock %}

  {% block body %}
  <form action="{% url 'accounts:genre' %}" method="POST">
    {% csrf_token %}
    {% for genre in genres %}
      <input type="checkbox" name="genre" value='{{genre.id}}' id="{{genre.name}}">
    {% endfor %}
    <div>
      <p class="genre-p"> 좋아하는 장르 세가지를 선택하세요 </p>
      <button class="btn btn-success genre-submit " type="submit">저장</button>
    </div>
  </form>  

  <header>
    <!-- 이 부분 배포시 삭제 -->
    {% if user.is_authenticated %}
    <a href="{% url 'accounts:logout' %}" style="color:white" >{{ user.username }}</a>
    {% endif %}
    <!-- 배포시 삭제 -->
  </header>
  <div class="genre-bg d-flex align-items-center">
    <div class="container">
      <div class="row">
        {% for genre in genres %}
          <div class="genre_box col-2">
            <label for="{{genre.name}}">{{genre.name}}</label>
          </div>
        {% endfor %}
      </div>
    </div>
  </div>
  <footer>
  </footer>
  {% endblock %}
  {% block script %}
  <script>
  document.querySelectorAll('label').forEach(label => {
    label.addEventListener('mouseover', function(event) {
      let genreName = event.target.getAttribute('for')
      document.querySelector('.genre-bg').style.backgroundImage  = "url('/static/accounts/images/" + genreName + ".jpg')"
    })
    label.addEventListener('click', function(event) {
      this.classList.toggle('select-label')
      })
  })
  const chkbox = document.getElementsByName("genre")
  chkbox.forEach(select => {
    select.addEventListener('change', function(event) {
      const genreSubmit = document.querySelector('.genre-submit')
      const genreP = document.querySelector('.genre-p')
      let chkCnt = 0;
      for(let i = 0; i<chkbox.length; i++)  {
        if(chkbox[i].checked) {
            chkCnt++;
          }
        }
        console.log(chkCnt)
        if(chkCnt>3){
          const genre = event.target.getAttribute('id')
          element = document.querySelector(`label[for=${genre}]`);
          select.checked = false
          element.classList.remove('select-label')
          alert("장르는 3개까지 선택 가능합니다.")
        }
        if(chkCnt === 3) {
          genreSubmit.style.display = "inline"
          genreP.style.display = "none"
        } else {
          genreSubmit.style.display = "none"
          genreP.style.display = "inline"
        }        
    })
  })

  </script>
{% endblock %}

accounts/templates/accounts/profile.html
{% extends 'base.html'%}

{% block css %}
  <style>
    * {
      color: white;
    }
    body {
      background: #131313;    
    }
    hr {
      color: white;
      border-color: white;
      background-color: white;
    }
  </style>
{% endblock %}
{% block title %}
  <title>프로필</title>
{% endblock %}


{% block body %}
  {% include '_navbar.html' %}
  <div class="container mt-5">
    <h1>{{user.username}} 프로필</h1><hr>
    <h2>좋아요한 영화</h2>
    <div class="row">
      {% for movie in user.like_movies.all %}
      <div class="col-3">
        <a href="{% url 'movies:detail' movie.movieid %}"><img width="100%" src="https://image.tmdb.org/t/p/w500{{movie.poster}}"></a>
        <p>{{movie.title}}</p>
      </div>
      {% endfor %}
    </div>

    <h2>평점 관리</h2>
    {% for comment in user.comment_set.all %}
      <span>{{comment.movie.title}} 평점</span>
      <span>{{comment.score}} | <span>{{comment.content}}</span></span>
      <form action="{% url 'movies:c_delete' comment.movie.movieid comment.pk %}" method="POST" class="d-inline ">
        {% csrf_token %}
        <button type="submit" class="btn btn-dark">평점삭제</button>
      </form> <hr> 
    {% endfor %}
  </div>
  {% include '_footer.html' %}
{% endblock %}

{% block script %}
{% endblock %}